import Foundation

extension MetricSnapshot {
    public func widgetCompactSnapshot() -> MetricSnapshot {
        // Keep fields that widgets can render in either shared-store or fallback sampling paths.
        // Strip detailed inventory lists and running app rows because those can contain user-created names.
        MetricSnapshot(
            cpuUsage: cpuUsage,
            cpuCoreUsages: cpuCoreUsages,
            hasCPUUsageReport: hasCPUUsageReport,
            physicalCoreCount: physicalCoreCount,
            logicalCoreCount: logicalCoreCount,
            activeProcessorCount: activeProcessorCount,
            cpuBrandName: nil,
            memoryUsedBytes: memoryUsedBytes,
            memoryTotalBytes: memoryTotalBytes,
            memoryFreeBytes: memoryFreeBytes,
            memoryWiredBytes: memoryWiredBytes,
            memoryCompressedBytes: memoryCompressedBytes,
            memoryCachedBytes: memoryCachedBytes,
            memorySwapUsedBytes: memorySwapUsedBytes,
            memorySwapTotalBytes: memorySwapTotalBytes,
            memorySwapAvailableBytes: memorySwapAvailableBytes,
            hasMemoryCompositionReport: hasMemoryCompositionReport,
            loadAverage: loadAverage,
            loadAverage5: loadAverage5,
            loadAverage15: loadAverage15,
            hasLoadAverageReport: hasLoadAverageReport,
            thermalState: thermalState,
            batteryPercent: batteryPercent,
            batteryIsCharging: batteryIsCharging,
            batteryPowerSource: batteryPowerSource,
            batteryTimeRemainingMinutes: batteryTimeRemainingMinutes,
            batteryCycleCount: batteryCycleCount,
            batteryHealth: batteryHealth,
            batteryCurrentCapacity: batteryCurrentCapacity,
            batteryMaxCapacity: batteryMaxCapacity,
            batteryDesignCapacity: batteryDesignCapacity,
            batteryVoltageMillivolts: batteryVoltageMillivolts,
            batteryAmperageMilliamps: batteryAmperageMilliamps,
            networkBytesPerSecond: networkBytesPerSecond,
            hasNetworkByteCounters: hasNetworkByteCounters,
            hasNetworkDirectionByteCounters: hasNetworkDirectionByteCounters,
            networkPathStatus: networkPathStatus,
            networkPathIsExpensive: networkPathIsExpensive,
            networkPathIsConstrained: networkPathIsConstrained,
            hasNetworkPathCostReport: hasNetworkPathCostReport,
            networkPathSupportsDNS: networkPathSupportsDNS,
            networkPathSupportsIPv4: networkPathSupportsIPv4,
            networkPathSupportsIPv6: networkPathSupportsIPv6,
            hasNetworkPathSupportReport: hasNetworkPathSupportReport,
            networkPathInterfaceKinds: networkPathInterfaceKinds,
            networkInBytesPerSecond: networkInBytesPerSecond,
            networkOutBytesPerSecond: networkOutBytesPerSecond,
            networkInterfaces: [],
            diskFreeBytes: diskFreeBytes,
            diskTotalBytes: diskTotalBytes,
            storageVolumes: [],
            processCount: 0,
            activeApplicationCount: 0,
            hiddenApplicationCount: 0,
            hasRunningAppCountReport: false,
            runningApps: [],
            gpuDevices: [],
            displays: [],
            uptimeSeconds: uptimeSeconds,
            hasUptimeReport: hasUptimeReport,
            osVersion: osVersion,
            kernelRelease: kernelRelease,
            timestamp: timestamp,
            schemaVersion: schemaVersion
        )
    }
}
