import Foundation

extension MetricSnapshot {
    public func widgetCompactSnapshot() -> MetricSnapshot {
        // Keep fields that widgets can render in either shared-store or fallback sampling paths.
        // Strip detailed inventory lists and running app rows because those can contain user-created names.
        MetricSnapshot(
            cpuUsage: cpuUsage,
            cpuCoreUsages: [],
            hasCPUUsageReport: hasCPUUsageReport,
            physicalCoreCount: 0,
            logicalCoreCount: logicalCoreCount,
            activeProcessorCount: activeProcessorCount,
            cpuBrandName: nil,
            memoryUsedBytes: memoryUsedBytes,
            memoryTotalBytes: memoryTotalBytes,
            memoryFreeBytes: 0,
            memoryWiredBytes: 0,
            memoryCompressedBytes: 0,
            memoryCachedBytes: 0,
            memorySwapUsedBytes: 0,
            memorySwapTotalBytes: 0,
            memorySwapAvailableBytes: 0,
            hasMemoryCompositionReport: false,
            loadAverage: loadAverage,
            loadAverage5: 0,
            loadAverage15: 0,
            hasLoadAverageReport: hasLoadAverageReport,
            thermalState: thermalState,
            batteryPercent: batteryPercent,
            batteryIsCharging: batteryIsCharging,
            batteryPowerSource: batteryPowerSource,
            batteryTimeRemainingMinutes: nil,
            batteryCycleCount: nil,
            batteryHealth: nil,
            batteryCurrentCapacity: nil,
            batteryMaxCapacity: nil,
            batteryDesignCapacity: nil,
            batteryVoltageMillivolts: nil,
            batteryAmperageMilliamps: nil,
            networkPathStatus: networkPathStatus,
            networkPathIsExpensive: networkPathIsExpensive,
            networkPathIsConstrained: networkPathIsConstrained,
            hasNetworkPathCostReport: hasNetworkPathCostReport,
            networkPathSupportsDNS: networkPathSupportsDNS,
            networkPathSupportsIPv4: networkPathSupportsIPv4,
            networkPathSupportsIPv6: networkPathSupportsIPv6,
            hasNetworkPathSupportReport: hasNetworkPathSupportReport,
            networkPathInterfaceKinds: networkPathInterfaceKinds,
            networkInterfaces: [],
            diskFreeBytes: diskFreeBytes,
            diskTotalBytes: diskTotalBytes,
            storageVolumes: [],
            processCount: 0,
            activeApplicationCount: 0,
            hiddenApplicationCount: 0,
            hasRunningAppCountReport: false,
            runningApps: [],
            gpuDevices: [],
            displays: [],
            uptimeSeconds: uptimeSeconds,
            hasUptimeReport: hasUptimeReport,
            osVersion: osVersion,
            kernelRelease: kernelRelease,
            timestamp: timestamp,
            schemaVersion: schemaVersion
        )
    }
}
